#!/bin/bash



export timeStart=
export timeEnd=

time_mesure_start(){
	timeStart=`date +%s`
}

time_mesure_end() {
    Name=$1
	timeEnd=`date +%s`

    local timeCost=$timeEnd-$timeStart
	local hour min
	hour=$((timeCost/3600))
	min=$(((timeCost-hour*60)/60))
	sec=$((timeCost-hour*3600-min*60))
	echo "$Name Total Time elapsed : $hour:$min:$sec (H:M:S)"
}



test_summart() {
	TOTAL_CACSE_CNT=$1
	FAILED_CACSE_CNT=$2
	TEST_RESULT_SUMMARY="$COMMAND_FILE test result : total $TOTAL_CACSE_CNT cases, failed $FAILED_CACSE_CNT."
	echo $TEST_RESULT_SUMMARY
	echo $TEST_RESULT_SUMMARY>>$TEST_RESULT_PATH/test_report.txt
}
