#!/bin/bash


SRC_SIZE_ARRAY=("1920 1080" "1280 720" "640 480")
SRC_FRAMERATE_ARRAY=("30/1" "60/1")

DST_SIZE_ARRAY=("1920 1080" "1280 720" "640 480")
DST_FRAMERATE_ARRAY=("30/1" "60/1")



# SRC_SIZE_ARRAY=("1920 1080")
# SRC_FRAMERATE_ARRAY=("60/1")

# DST_SIZE_ARRAY=("1920 1080")
# DST_FRAMERATE_ARRAY=("60/1")



# For dmabuf, it needn't copy, High performance! 
# For mmap, it need copy, Low performance! 
IO_MODE_ARRAY=("dmabuf" "mmap")


